//
//  CreateTodoPresenter.swift
//  TODO
//
//  Created by Chang gyun Park on 2021/01/19.
//  Copyright (c) 2021 nobleidea. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateTodoPresentationLogic
{
  func presentSomething(response: CreateTodo.Something.Response)
}

class CreateTodoPresenter: CreateTodoPresentationLogic
{
  weak var viewController: CreateTodoDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CreateTodo.Something.Response)
  {
    let viewModel = CreateTodo.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
